"use client";
import React, { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

// --- LEGAL CONTENT DATA ---
const termsData = [
  {
    id: "acceptance",
    title: "1. Acceptance and Scope of Terms",
    points: [
      "By accessing the 5onam AI platform, you enter into a binding legal agreement with Zen-Tech Intelligence Wing (ZTIW).",
      "These terms apply to all usage of the 5onam AI web interface, its heuristic routing infrastructure, and associated native AI tools.",
      "Users must possess the legal capacity in their jurisdiction to enter into binding contracts to utilize this service.",
      "ZTIW reserves the exclusive right to modify, amend, or replace these Terms of Service at any time without prior direct notice.",
      "Continued utilization of the 5onam AI ecosystem following any modifications constitutes your explicit acceptance of the revised terms.",
    ],
  },
  {
    id: "services",
    title: "2. Description of 5onam AI Services",
    points: [
      "5onam AI operates as a multimodal enterprise generative agent capable of parsing text, vision, documents (PDF/CSV), and generating charts.",
      "The platform features specialized dynamic personas, including Dev Sanu (Coding), Richa (Marketing), Prof Amruta (English), and Chef Manu (Cooking).",
      "Services include access to the Zen-Tech Code Canvas, PPT SaaS generation tools, and advanced Deep Research web capabilities.",
      "The platform utilizes a Neural Memory Vault to selectively extract and store user preferences locally to personalize future interactions.",
      "Voice output features and UI tools are provided on an experimental basis and rely on third-party synthesizers for execution.",
    ],
  },
  {
    id: "accounts",
    title: "3. Account Security and Access",
    points: [
      "Users are required to provide accurate, current, and complete information during the Zen-Tech account registration process.",
      "You hold sole responsibility for safeguarding your password and securing your authentication credentials against unauthorized access.",
      "Sharing accounts, transferring access keys, or attempting to bypass authentication protocols is strictly prohibited.",
      "ZTIW reserves the right to suspend or permanently terminate access to the routing endpoints at our sole discretion.",
      "Users must immediately notify the Zen-Tech administration team if they suspect a breach of their account security.",
    ],
  },
  {
    id: "aup",
    title: "4. Acceptable Use Policy (AUP)",
    points: [
      "Users are strictly forbidden from utilizing 5onam AI to generate illegal, defamatory, abusive, or explicitly harmful content.",
      "Attempting to reverse-engineer, decompile, or bypass the platform's API failover logic or security protocols is a violation of these terms.",
      "The deployment of automated scripts, scrapers, or botnets that generate excessive requests against our servers is prohibited.",
      "Users must not input prompt injections, malicious executable payloads, or recursive loops into the AI terminal.",
      "Violations of this Acceptable Use Policy will result in immediate termination of services and potential legal action.",
    ],
  },
  {
    id: "privacy",
    title: "5. Data Privacy and Storage Limits",
    points: [
      "Active session data and chat histories are persisted exclusively on your local device utilizing the browser's Web Storage API.",
      "To process queries, inputs are transiently routed to authorized third-party Large Language Model (LLM) endpoints.",
      "Users are strictly prohibited from inputting highly sensitive Personally Identifiable Information (PII) or Protected Health Information (PHI).",
      "Because chat data is localized, users retain full control and may permanently delete their data by clearing their browser storage.",
      "All data handling procedures are subject to the broader Zen-Tech Privacy Policy, which acts alongside this agreement.",
    ],
  },
  {
    id: "intellectual-property",
    title: "6. Intellectual Property Rights",
    points: [
      "Users retain all original intellectual property rights to the specific documents, CSVs, and proprietary data they upload.",
      "ZTIW retains exclusive ownership of the 5onam AI UI/UX design, custom personas, orchestration architecture, and routing algorithms.",
      "Output generated by the AI is licensed to the user for personal or corporate productivity, subject to third-party API provider rules.",
      "Copying, distributing, or attempting to sell the 5onam AI core architecture or branding elements is strictly forbidden.",
      "Any feedback, bug reports, or feature suggestions submitted to Zen-Tech may be implemented without compensation to the user.",
    ],
  },
  {
    id: "third-party",
    title: "7. Third-Party Integrations and Models",
    points: [
      "5onam AI acts as an orchestration layer utilizing frontier models including Gemini 3.1 Pro, GPT-5.4 Series, Llama 4, and DeepSeek R1.",
      "Service availability is directly dependent on the uptime, rate limits, and stability of these third-party API providers.",
      "ZTIW cannot guarantee uninterrupted service if upstream generative endpoints experience outages or latency.",
      "By utilizing the platform, users also consent to the transient processing policies of our respective model providers.",
      "Zen-Tech claims no liability for the failure, deprecation, or data loss caused by external third-party integrations.",
    ],
  },
  {
    id: "disclaimers",
    title: "8. Disclaimers and AI Hallucinations",
    points: [
      "Due to the probabilistic nature of Generative AI, outputs may be factually inaccurate, incomplete, biased, or hallucinated.",
      "The 5onam AI service is provided on a strict \"AS IS\" and \"AS AVAILABLE\" basis without implied warranties.",
      "Users are solely responsible for independently verifying all generated code, data charts, and factual claims before production use.",
      "Under no circumstances does information provided by 5onam AI constitute professional medical, legal, or financial advice.",
      "ZTIW disclaims all implied warranties of merchantability, fitness for a particular purpose, and non-infringement.",
    ],
  },
  {
    id: "liability",
    title: "9. Limitation of Liability",
    points: [
      "To the maximum extent permitted by law, ZTIW shall not be liable for any indirect, incidental, special, or punitive damages.",
      "Our maximum financial liability to any user shall not exceed the amount paid by the user for the service in the preceding month.",
      "ZTIW is completely immune from liability regarding data corruption, business interruption, or system failures.",
      "The user assumes all inherent risks associated with compiling, running, or deploying code generated by the Dev Sanu persona.",
      "These limitations apply regardless of whether the liability is based on contract, tort, negligence, or strict liability.",
    ],
  },
  {
    id: "jurisdiction",
    title: "10. Governing Law and Dispute Resolution",
    points: [
      "These Terms of Service shall be governed by and construed in accordance with the laws of Maharashtra, India.",
      "Any disputes arising from the use of 5onam AI fall under the exclusive jurisdiction of the courts located in Maharashtra.",
      "Users agree to attempt informal negotiation and mediation with the Zen-Tech administration team prior to initiating litigation.",
      "Unresolved disputes will be subject to binding arbitration under local technology and cyber law regulations.",
      "All formal legal notices and communications must be directed to the official administration at zentechindiaofficial@gmail.com.",
    ],
  },
];

export default function TermsPage() {
  const [activeSection, setActiveSection] = useState("");

  // Scroll spy logic for Table of Contents
  useEffect(() => {
    const handleScroll = () => {
      let current = "";
      for (const section of termsData) {
        const element = document.getElementById(section.id);
        if (element) {
          const rect = element.getBoundingClientRect();
          // Adjust threshold based on header height
          if (rect.top <= 200) {
            current = section.id;
          }
        }
      }
      setActiveSection(current);
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const scrollToSection = (e: React.MouseEvent<HTMLAnchorElement>, id: string) => {
    e.preventDefault();
    const element = document.getElementById(id);
    if (element) {
      const offset = 120; // Accounts for the sticky header
      const bodyRect = document.body.getBoundingClientRect().top;
      const elementRect = element.getBoundingClientRect().top;
      const elementPosition = elementRect - bodyRect;
      const offsetPosition = elementPosition - offset;

      window.scrollTo({
        top: offsetPosition,
        behavior: "smooth",
      });
    }
  };

  return (
    <main className="min-h-screen bg-white text-gray-800 font-sans selection:bg-purple-200 selection:text-purple-900">
      
      {/* Sticky Header */}
      <header className="sticky top-0 z-50 w-full bg-white/90 backdrop-blur-md border-b border-purple-100 px-6 py-4 flex items-center justify-between shadow-sm">
        <Link href="/login" className="flex items-center gap-2 text-purple-600 hover:text-purple-800 transition-colors font-semibold text-sm">
          <ArrowLeft size={18} />
          Back to Login
        </Link>
        <div className="font-extrabold text-xl tracking-tight bg-gradient-to-r from-purple-700 to-purple-500 bg-clip-text text-transparent">
          5onam AI
        </div>
      </header>

      <div className="max-w-7xl mx-auto px-6 py-10 lg:py-16 flex flex-col-reverse lg:flex-row gap-10 lg:gap-16">
        
        {/* Left Side: 70% Content */}
        <div className="w-full lg:w-[70%]">
          <div className="mb-12 border-b border-gray-100 pb-8">
            <h1 className="text-4xl sm:text-5xl font-extrabold text-gray-900 mb-4 tracking-tight">
              Terms of Service
            </h1>
            <p className="text-purple-600 font-semibold text-sm uppercase tracking-widest">
              Zen-Tech Intelligence Wing • Effective Date: March 2026
            </p>
          </div>

          <div className="space-y-16 text-gray-600 leading-relaxed">
            {termsData.map((section, index) => (
              <section key={section.id} id={section.id} className="scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-3">
                  <span className="w-9 h-9 rounded-xl bg-purple-100 text-purple-700 flex items-center justify-center text-sm shadow-sm border border-purple-200">
                    {index + 1}
                  </span>
                  {section.title.split('. ')[1]} {/* Strips the number from the title since we use a badge */}
                </h2>
                <ul className="space-y-4 pl-3">
                  {section.points.map((point, ptIndex) => (
                    <li key={ptIndex} className="flex items-start gap-3">
                      <span className="w-1.5 h-1.5 rounded-full bg-purple-400 mt-2.5 shrink-0"></span>
                      <span className="text-[15px]">{point}</span>
                    </li>
                  ))}
                </ul>
              </section>
            ))}
          </div>
        </div>

        {/* Right Side: 30% Sticky Table of Contents */}
        <div className="w-full lg:w-[30%]">
          <div className="sticky top-28 p-6 bg-[#FAFAFA] border border-purple-100 rounded-2xl shadow-sm">
            <h3 className="text-xs font-extrabold text-purple-900 uppercase tracking-widest mb-5">
              Table of Contents
            </h3>
            <nav className="flex flex-col gap-3.5">
              {termsData.map((section) => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  onClick={(e) => scrollToSection(e, section.id)}
                  className={`text-[13px] font-medium transition-all duration-300 leading-snug ${
                    activeSection === section.id
                      ? "text-purple-700 translate-x-2 font-bold"
                      : "text-gray-500 hover:text-purple-500"
                  }`}
                >
                  {section.title}
                </a>
              ))}
            </nav>
          </div>
        </div>

      </div>
    </main>
  );
}